name: Build
on:
  push:
    branches:
      - "eclair"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Composer install
        uses: php-actions/composer@v6

      - uses: actions/upload-artifact@v3
        with:
          name: PiwigoOpenIdConnect
          path: .
